### ISSUE TITLE
SF Symbols 2 is available

### ISSUE THREAD

**Issue by delef** [virskor/flutter_sfsymbols#3]
Have you plans for adding support SF Symbols 2?

**Comment by virskor** [comment]
@delef i think i will do that

**Comment by virskor** [comment]
we already try, but there are some troubles when using new fonts. i will close this issue and migrate this package as soon as possible.

**Comment by nilsreichardt** [comment]
@virskor Any updates on this?

**Comment by virskor** [comment]
> @virskor Any updates on this?

Flutter has new Cupertino icon assets updated. please use official package. This package is not going to update.

**Comment by nilsreichardt** [comment]
> Flutter has new Cupertino icon assets updated. 

Ah, great!

> This package is not going to update.

Would be great to update the `README.md` and mark this package as discontinued on pub.dev.
